### ISSUE TITLE
Beam Search

### ISSUE THREAD

**Issue by jonas-da** [rsommerfeld/trocr#4]
Hi, 

thanks for the great and simple repo! 
Is the generation of the predict a greedy or a beam Search approach? 
If you know how to implement an beam search generation, then I would be very happy if you could help me out! 

Cheers, Jonas

**Comment by rsommerfeld** [comment]
Hi, I'm glad you enjoy using the repo! According to the original TrOCR paper, the Decoder already uses beam search to generate the output, see https://arxiv.org/pdf/2109.10282.pdf
