### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by 123akopf321** [rsommerfeld/trocr#6]
Can you also provide a pre-trained model for testing?

**Comment by rsommerfeld** [comment]
There is already a pre-trained model available for testing from huggingface. No need to download it manually, you can just use it by adding the `--no-local-model` flag. See the section on Inference (Prediction) in the readme:
``` Python
python -m src predict data/* --no-local-model  # uses the pretrained huggingface model
```

Is this what you were thinking of?
