### ISSUE TITLE
Model.eval()

### ISSUE THREAD

**Issue by dparres** [rsommerfeld/trocr#9]
Hi!

During training you don’t use model.eval() when you call to validate() function. It could affect to model performance?

**Comment by rsommerfeld** [comment]
Hi, thanks for noticing this! I will push a new commit shortly

As a side node: The model seems to be in eval-mode by default, which means that after loading a pre-trained model and using it for inference, there should not be any impact on performance. I would expect the validation accuracies to be affected, but have not tested if the impact is actually measurable. If you did, feel free to update here as I'm curious!
